name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Deploy application
        env:
          DEPLOYMENT_ENV: "production"
        run: |
          echo "Starting deployment process..."
          # Add deployment commands here, e.g., uploading to a server, deploying to a cloud service, etc.
          echo "Deployment completed."

       
